import * as React from 'react';
import Icon, { IconProps } from './Icon';

export enum ICON {
  BELL = 'bell',
  BUTTERY_HALF = 'butterfly-half',
  CODE = 'code',
  COMMENT_DOTS = 'comment-dots',
  COMMENTS = 'comments',
  CHART_BAR = 'chart-bar',
  CHART_PIE = 'chart-pie',
  CHART_RADAR = 'chart-radar',
  DESKTOP = 'desktop',
  EYE = 'eye',
  GEARS = 'gears',
  PAINTBRUSH = 'paint-brush',
  PHONE = 'phone',
  PLUG = 'plug',
  ROBOT = 'robot',
  SLIDERS = 'sliders',
  TAGS = 'tags',
  TYPEWRITER = 'typewriter',
  USER = 'user',
  USER_ONLINE = 'briefcase',
  USER_PAUSE = 'coffee',
  LOADING = 'circle-notch',
  LOADING_IDLE = 'circle',
  ADD_USER = 'user-plus',
  SEARCH = 'search',
  COPY = 'copy',
  LABEL = 'tag',
  LABELS = 'tags',
  FILE_EXCHANGE = 'upload',
  SHORTCUTS = 'keyboard',
  TRANSFER = 'exchange-alt',
  TRANSLATE = 'language',
  SECURE_DATA = 'lock',
  SCREEN_SHARE = 'screencast',
  ADMIN = 'gear',
  MESSAGING = 'comments',
  SUPERVISOR = 'eye',
  STATISTICS = 'chart-bar',
  DASHBOARD = 'user-chart',
  HELP = 'question-circle',
  NEWS = 'newspaper',
  SQUAWKBOX = 'bullhorn',
  LOGOUT = 'sign-out-alt',
  CHAT_ARCHIVE = 'clock-rotate-left',
  RECENT_CHATS = 'inbox',
  LIVE_CHATS = 'headset',
  NO_CONVERSATION = 'comment-slash',
  NO_SEARCH_RESULT = 'face-sad-tear',
  SELECTED = 'check',
  VISITOR_MESSAGE = 'face-smile',
  WHISPER_MESSAGE = 'face-shush',
  EMOJI = 'face-awesome',
  SEND_MESSAGE = 'paper-plane',
  CHANNEL_GOOGLE = 'google',
  CHANNEL_FACEBOOK = 'facebook',
  CHANNEL_WHATSAPP = 'whatsapp',
  CHANNEL_SMS = 'comment-sms',
  CHANNEL_POLL = 'globe',
  CHANNEL_WE_CHAT = 'comment',
  WINDOW = 'window',
  WINDOW_MINIMIZE = 'window-minimize',
  WINDOW_MAXIMIZE = 'window-maximize',
  WINDOW_RESTORE = 'window-restore',
  WINDOW_CLOSE = 'window-close',
  WINDOW_ATTACH = 'angle-down',
  WINDOW_DETACH = 'angle-up',
  CLOSE = 'close',
  SWITCH_WIDGET = 'right-left-large',
  MAP = 'map-location-dot',
  UNKNOWN_LOCATION = 'location-question',
  CENTER_VIEW = 'location-crosshairs',
  TEMPERATURE = 'temperature-quarter',
  LOCATION = 'location-dot',
  MEDIA_LIBRARY = 'photo-film-music',
  AGENT_LINKS = 'link',
  KNOWLEDGE_BASE = 'book-open-cover',
  CONTACT_INFO = 'info-circle',
  REMOVE_FILTER = 'filter-slash',
  DOWNLOAD = 'download',
  UPLOAD = 'file-arrow-up',
  OPEN = 'arrow-up-right-from-square',
  TEAMSUPPORT = 'teamsupport',
  LOW_RATING = 'face-frown',
  MEDIUM_RATING = 'face-neutral',
  HIGH_RATING = 'face-smile',
  STAR = 'star',
  HALF_STAR = 'star-half-stroke',
  WEATHER = 'cloud-bolt-sun',
  SUCCESS = 'check',
  FAILURE = 'circle-exclamation',
  AI = 'sparkles',
  REFRESH = 'refresh',
  EDIT = 'edit',
  SORT = 'sort',
  SORT_ASC = 'sort-up',
  SORT_DESC = 'sort-down',
  WARNING = 'exclamation-triangle',
  TYPING = 'message-dots',
  MESSAGE = 'message',
  CANCEL = 'times',
  CHECKED = 'check',
  GROUP_CHAT = 'users',
  PRIVATE_CHAT = 'user',
  FILTER = 'filter',
  LOCKED = 'lock',
  UNLOCKED = 'lock-open',
  VISIBLE = 'eye',
  INVISIBLE = 'eye-slash',
  TABLE = 'table-layout',
  EXPAND_RIGHT = 'angle-right',
  EXPAND_LEFT = 'angle-left',
  EXPAND_DOWN = 'angle-down',
  EXPAND_UP = 'angle-up',
  CLAIM = 'hand',
  SAVE = 'save',
  DELETE = 'trash-xmark',
  LOAD = 'folder-open',
  NEW = 'plus',
  COMMAND = 'terminal',
  RADIO_UNSELECTED = 'circle',
  RADIO_SELECTED = 'circle-dot',
  INFO = 'info-circle',
  SCROLL_DOWN = 'down-to-line',
  DATE = 'calendar',
  TICKET = 'ticket',
  TRASH = 'trash',
  OPTIONS = 'ellipsis-v',
  TRANSCRIPT = 'message-text',
  EXPAND_SCREEN = 'expand',
  COLLAPSE_SCREEN = 'compress',
  ZOOM_IN = 'magnifying-glass-plus',
  ZOOM_OUT = 'magnifying-glass-minus',
  GRID = 'grid',
  SLIDESHOW = 'rectangle-vertical-history',
  TUTORIAL = 'graduation-cap',
  CHANGELOG = 'square-list',
  FEEDBACK = 'comment-pen',
  ROTATE_LEFT = 'arrow-rotate-left',
  ROTATE_RIGHT = 'arrow-rotate-right',
  RESET = 'octagon-xmark',
  IMAGE = 'image',
  INCOGNITO = 'user-secret',
  WRITE = 'pen',
  PAUSE = 'pause',
  PLAY = 'play',
  STOP = 'stop',
  NOTE = 'note',
  MESSAGE_BUBBLE = 'messages',
  MESSAGE_INLINE = 'message-lines',
  HYPERLINK = 'link-horizontal',
  TEXT = 'text',
  GRIP = 'grip-dots-vertical',
  BOLD = 'bold',
  ITALIC = 'italic',
  UNDERLINE = 'underline',
  STRIKETHROUGH = 'strikethrough',
  QUOTE = 'block-quote',
  LINK = 'link',
  LIST = 'list',
  EMAIL = 'envelope',
  GIF = 'gif',
  MUTE = 'volume-off',
  INTEGRATION = 'cloud-check',
  CONTEXT = 'lightbulb-on',
  MORE = 'angles-right',
  SENTIMENT = 'message-smile',
}

type IconOptions = {
  size?: string;
  isSpinning?: boolean;
  library?: 'fal' | 'fas' | 'far' | 'fab' | 'custom';
  color?: string;
  inline?: boolean;
};

export const useIcon = () => {
  const i = (iconName: ICON | string, options?: IconOptions) => {
    const {
      isSpinning = false,
      library = 'fal',
      size,
      color,
      inline,
    } = options || {};

    return (
      <Icon
        icon={iconName as IconProps['icon']}
        isSpinning={isSpinning}
        library={library}
        size={size as IconProps['size']}
        color={color}
        inline={inline}
      />
    );
  };

  return { i };
};
