import i18n from '../../i18n';
import { WeatherImage } from 'hubv2/types/requests';

export const weatherIconsMap: { [key in WeatherImage]: string } = {
  chanceflurries: 'cloud',
  chancerain: 'rain-2',
  chancesleet: 'rain-5',
  chancesnow: 'snowing-1',
  chancetstorms: 'light-bolt-1',
  clear: 'sun-1',
  cloudy: 'sky',
  flurries: 'cloud',
  fog: 'fog',
  hazy: 'fog',
  mostlycloudy: 'cloud-3',
  mostlysunny: 'cloudy-1',
  partlycloudy: 'cloudy-1',
  partlysunny: 'cloudy-1',
  sleet: 'rain-7',
  rain: 'rain',
  snow: 'snow',
  sunny: 'sun-1',
  tstorms: 'thunder',
  nt_chanceflurries: 'cloud',
  nt_chancerain: 'rain-2',
  nt_chancesleet: 'rain-5',
  nt_chancesnow: 'snowing-1',
  nt_chancetstorms: 'light-bolt-1',
  nt_clear: 'sun-1',
  nt_cloudy: 'sky',
  nt_flurries: 'cloud',
  nt_fog: 'fog',
  nt_hazy: 'fog',
  nt_mostlycloudy: 'cloud-3',
  nt_mostlysunny: 'cloudy-1',
  nt_partlycloudy: 'cloudy-1',
  nt_partlysunny: 'cloudy-1',
  nt_sleet: 'rain-7',
  nt_rain: 'rain',
  nt_snow: 'snow',
  nt_sunny: 'sun-1',
  nt_tstorms: 'thunder',
};

export const weatherDescriptionMap = {
  chanceflurries: i18n.t('Chance of Flurries'),
  chancerain: i18n.t('Chance of Rain'),
  chancesleet: i18n.t('Chance of Sleet'),
  chancesnow: i18n.t('Chance of Snow'),
  chancetstorms: i18n.t('Chance of Thunderstorms'),
  clear: i18n.t('Clear'),
  cloudy: i18n.t('Cloudy'),
  flurries: i18n.t('Flurries'),
  fog: i18n.t('Fog'),
  hazy: i18n.t('Hazy'),
  mostlycloudy: i18n.t('Mostly Cloudy'),
  mostlysunny: i18n.t('Mostly Sunny'),
  partlycloudy: i18n.t('Partly Cloudy'),
  partlysunny: i18n.t('Partly Sunny'),
  sleet: i18n.t('Sleet'),
  rain: i18n.t('Rain'),
  snow: i18n.t('Snow'),
  sunny: i18n.t('Sunny'),
  tstorms: i18n.t('Thunderstorms'),
  nt_chanceflurries: i18n.t('Chance of Flurries'),
  nt_chancerain: i18n.t('Chance of Rain'),
  nt_chancesleet: i18n.t('Chance of Sleet'),
  nt_chancesnow: i18n.t('Chance of Snow'),
  nt_chancetstorms: i18n.t('Chance of Thunderstorms'),
  nt_clear: i18n.t('Clear'),
  nt_cloudy: i18n.t('Cloudy'),
  nt_flurries: i18n.t('Flurries'),
  nt_fog: i18n.t('Fog'),
  nt_hazy: i18n.t('Hazy'),
  nt_mostlycloudy: i18n.t('Mostly Cloudy'),
  nt_mostlysunny: i18n.t('Mostly Sunny'),
  nt_partlycloudy: i18n.t('Partly Cloudy'),
  nt_partlysunny: i18n.t('Partly Sunny'),
  nt_sleet: i18n.t('Sleet'),
  nt_rain: i18n.t('Rain'),
  nt_snow: i18n.t('Snow'),
  nt_sunny: i18n.t('Sunny'),
  nt_tstorms: i18n.t('Thunderstorms'),
};
